# action.yml
name: 'CodeQL Debugger'
description: 'GitHub Advance Security CodeQL Debugger Action'
author: GeekMasher

inputs:
  databases:
    description: 'CodeQL Database Folder Location'
    required: false
    default: /home/runner/work/_temp/codeql_databases/java
  database_name:
    description: 'CodeQL Database Name (default: java)'
    required: false
    default: "java"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -d ${{ inputs.databases }}
    - -dn ${{ inputs.database_name }}
